---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sampleweb
  namespace: sampleweb
  labels:
    app: sampleweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleweb
  template:
    metadata:
      labels:
        app: sampleweb
    spec:
      containers:
      - name: sampleweb
        image: "dheerajayati91/samplewebapp:latest"
        ports:
          - containerPort: 9004
---
apiVersion: v1
kind: Service
metadata:
  name: sampleweb
  namespace: sampleweb
spec:
  selector:
    app: LoginWebApp
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 9004
    port: 80
